### ISSUE TITLE
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied

### ISSUE THREAD

**Issue by veera2019** [bitnami/bitnami-docker-mongodb#178]
i have installed mongodb using helm install stable/mongodb command after installing that mongodb pod status showing crashloopbackoff and i have seen logs it's showing error like mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied.
I am installing mongodb on kubernetes in windows environment
Error message
�[38;5;6m �[38;5;5m05:25:28.91 �[0m
�[38;5;6m �[38;5;5m05:25:28.92 �[0m�[1mWelcome to the Bitnami mongodb container�[0m
�[38;5;6m �[38;5;5m05:25:28.92 �[0mSubscribe to project updates by watching �[1mhttps://github.com/bitnami/bitnami-docker-mongodb�[0m
�[38;5;6m �[38;5;5m05:25:28.92 �[0mSubmit issues and feature requests at �[1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues�[0m
�[38;5;6m �[38;5;5m05:25:28.92 �[0mSend us your feedback at �[1mcontainers@bitnami.com�[0m
�[38;5;6m �[38;5;5m05:25:28.92 �[0m
�[38;5;6m �[38;5;5m05:25:28.92 �[0m�[38;5;2mINFO �[0m ==> ** Starting MongoDB setup **
�[38;5;6m �[38;5;5m05:25:28.93 �[0m�[38;5;2mINFO �[0m ==> Validating settings in MONGODB_* env vars...
�[38;5;6m �[38;5;5m05:25:28.93 �[0m�[38;5;2mINFO �[0m ==> Initializing MongoDB...
�[38;5;6m �[38;5;5m05:25:28.93 �[0m�[38;5;2mINFO �[0m ==> Deploying MongoDB from scratch...
mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied

Somebody can give me the solution

**Comment by marcosbc** [comment]
Hi @veera2019, could you update your deployment/create a new one with the setting below? It is necessary when your PVCs are handled by NFS servers.

    --set volumePermissions.enabled=true

**Comment by veera2019** [comment]
> Hi @veera2019, could you update your deployment/create a new one with the setting below? It is necessary when your PVCs are handled by NFS servers.
> 
> ```
> --set volumePermissions.enabled=true
> ```


Thanks a lots now it's working fine but after executing helm install i got output like below


MongoDB can be accessed via port 27017 on the following DNS name from within your cluster:

    velocity-mongo-mongodb.default.svc.cluster.local

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default velocity-mongo-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run --namespace default velocity-mongo-mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host velocity-mongo-mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/velocity-mongo-mongodb 27017:27017 &
    mongo --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD


I have executed the above commands but when i am executing the connect to your database command below i am getting authentication error.
  kubectl run --namespace default velocity-mongo-mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host velocity-mongo-mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
 
after executing this command velocity-mongo-mongodb-client pod gettting CrashLoopBackOff  and pod logs showing below error

MongoDB shell version v4.0.13
connecting to: mongodb://velocity-mongo-mongodb:27017/admin?authSource=admin&gssapiServiceName=mongodb
2019-10-28T08:44:35.978+0000 E QUERY    [js] Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:344:17
@(connect):2:6
exception: connect failed

**Comment by veera2019** [comment]
Now MongoDB pods running fine but if i run my application i am getting MongoError: Authentication failed.

server - [39mDatabase cannot be reached: Authentication failed.


{ MongoError: Authentication failed.
    at /application-api/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/application-api/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/application-api/node_modules/mongodb-core/lib/connection/pool.js:540:5)
 at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by marcosbc** [comment]
Hi @veera2019, that happens if you had a previous deployment that failed but the volume is still present. In that case, the MongoDB chart will try to use that existing volume, in order to be able to use the data from a previous installation.

If you did not have any relevant data you can remove the PVC (persistent volume claim). For that, first obtain the proper PVC name for your previous MongoDB install:

    kubectl get pvc

And then remove it:

    kubectl delete pvc NAME

**Comment by veera2019** [comment]
Hi @marcosbc  mongodb pod running fine and only one PVC running but still i am facing same issue in my application pod logs showing Mongoerror
Error starting application:  { MongoError: Authentication failed.
 [INFO] mongo - [39mconnecting...
 [WARN] server - [39mDatabase cannot be reached: Authentication failed.
 [WARN] server - [39mRetrying database connection...

**Comment by marcosbc** [comment]
Hi @veera2019, that error seems to indicate that the database connection credentials are wrong, which is a separate issue.

Could you describe how you are configuring your application? Could you confirm you are using the MongoDB "root" user with the password obtained from the command below:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default velocity-mongo-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

**Comment by veera2019** [comment]
Hi @marcosbc , Thank you it's working fine now and my application also running successfully.

**Comment by veera2019** [comment]
Hi @marcosbc i am installing mongodb in AWS instance using below command 
helm install --set mongodbRootPassword=welcome,mongodbUsername=mongo,mongodbDatabase=velocity  --set volumePermissions.enabled=true --name velocity-mongo stable/mongodb

i am getting error like mongodb pod and pvc status showing pending only
in PVC logs showing error like **no persistent volumes available for this claim and no storage class is set**
in mongodb pod logs showing like   **pod has unbound immediate PersistentVolumeClaims**
So can you please suggest me to resolve this issue

Thanks
veerareddy

**Comment by javsalgar** [comment]
Hi,

I see that you reopened the issue. Could you confirm if you are experiencing more problems?

**Comment by veera2019** [comment]
i have launched volume and attached to ec2 instance master node and created pv from kubernetes master .
i am installing mongodb using below command
helm install --set mongodbRootPassword=###,mongodbUsername=mongo,mongodbDatabase=### --set volumePermissions.enabled=true --name mongo stable/mongodb

After running this command pvc pod running fine and mongodb pod status showing init:0/1
if i describe the mongodb pod i am getting error like

****Warning FailedMount 14m (x18 over 57m) kubelet, ip Unable to mount volumes for pod "mongo-mongodb-7ff758c779_default()": timeout expired waiting for volumes to attach or mount for pod "default"/"mongo-mongodb-7ff758c779". list of unmounted volumes=[data]. list of unattached volumes=[data default-token]**

**mount: /var/lib/kubelet/pods/b9ce4962-ff8e-11e9-a2d3/volumes/kubernetes.io~aws-ebs/mongo: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-##does not exist.****

Can you give me the solution

**Comment by javsalgar** [comment]
Hi,

It seems to me that this issue is more related to the Kubernetes platform you are using rather than the chart itself. Could you execute kubectl get pvc to confirm it that the PV you created is bound?

**Comment by jmpolvera** [comment]
I made this in the host directory and worked:

sudo chown -R 1001:1001 <directory>


https://techoverflow.net/2018/12/15/solving-bitnami-docker-redmine-cannot-create-directory-bitnami-mariadb-permission-denied/

**Comment by RyanGuyCode** [comment]
> chown -R 1001:1001

which directory would this be ? I do get the same error...
`mongo_1               |  04:21:51.15 INFO  ==> Deploying MongoDB from scratch...
mongo_1               | mkdir: cannot create directory '/bitnami/mongodb': Permission denied`

**Comment by javsalgar** [comment]
Hi @RyanGuyCode 

Could you provide more information about the volume system you are using?

**Comment by RyanMilton** [comment]
@javsalgar I am deploying this within openmediavault NAS, with external drives connected for storage. This is a home set up. I'm no expert here on many levels.
EG:
`/dev/disk/by-label/East500              /srv/dev-disk-by-label-East500  ext4    defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl  0 2`

I am deploying this via portainer as a stack.
hopefully this is correct: 

`version: "2"
services:
  speedlogger-web:
    image: brennentsmith/internet-speed-logger
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    volumes:
      - /srv/dev-disk-by-label-East500/AppData/speedlogger/:/data/config
  speedlogger-runner:
    image: brennentsmith/internet-speed-logger
    depends_on:
      - speedlogger-web
    restart: always
    entrypoint:
      - node
      - run-speedtest.js
      - daemon
    volumes:
      - /srv/dev-disk-by-label-East500/AppData/speedlogger/:/data/config
  mongo:
    image: bitnami/mongodb
    expose:`

**Comment by javsalgar** [comment]
Hi,

It is highly likely that the volume you are mounting does not have the proper permissions for the non-root user to create files and directories. You would need to make the permissions more open by using chmod. Would that be possible in your case?

**Comment by RyanMilton** [comment]
I think it would be possible. where do I specify? In the compose file?

**Comment by RyanMilton** [comment]
ok, so I was able to change permissions and mongodb started! yay. Next hurdle is that the speedlogger-web and speedlogger-runner are both thowing errors in the logfile. Making me think I am missing some files.

`WARNING: No configurations found in configuration directory:/data/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/data/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^
Error: Configuration property "db.connectionString" is not defined
    at Config.get (/data/node_modules/config/lib/config.js:182:11)
    at Object.<anonymous> (/data/db/index.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/run-speedtest.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)`

**Comment by Shilagrawal** [comment]
I am facing same issue while deploying on AWS EBS instances while using K8s 1.23 ,
helm install my-release bitnami/mongodb-sharded --namespace=mongodb --set global.storageClass=vxflexos-xfs --set mongodbRootPassword=mongodb123,mongodbUsername=mongodb,mongodbPassword=mongodb123,mongodbDatabase=ycsb --set volumePermissions.enabled=true --set replicaSet.enabled=true --set shards=8 --set configsvr.replicas=1 --set configsvr.persistence.size=150Gi --set mongos.replicas=1 --set shardsvr.dataNode.replicas=1 --set shardsvr.persistence.size=1.5Ti --set shardsvr.dataNode.resources.requests.memory=72Gi --set shardsvr.dataNode.resources.requests.cpu=24 --set configsvr.resources.requests.memory=16Gi --set mongos.resources.requests.memory=16Gi --set volumePermissions.enabled=true

[root@Mongo-K8Master ec2-user]# kubectl logs -n mongodb my-release-mongodb-sharded-shard1-data-0
13:22:29.35 INFO ==> Setting node as primary
mongodb 13:22:29.38
mongodb 13:22:29.38 Welcome to the Bitnami mongodb-sharded container
mongodb 13:22:29.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb 13:22:29.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb 13:22:29.38
mongodb 13:22:29.38 INFO ==> ** Starting MongoDB Sharded setup **
mongodb 13:22:29.42 INFO ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb': Permission denied

If i try to use chown permissions to /bitmani/mongodb-- it says directory doesnt exist
I tried using --set volumePermissions.enabled=true option but no luck
Since i am just added helm bitmani repo and then doing the install using help I dont have any docker-compose yaml to edit and dont know where this securitycontext file or section in which file needs to be edited to make this work
Any help is appreciated ! Not sure if its AWS side of issue

**Comment by javsalgar** [comment]
Could you launch it with diagnosticMode.enabled=true, enter the containers and check what the permissions of the mounted volumes are?

**Comment by Shilagrawal** [comment]
With diagnostic mode the pods ran fine when i exec 

I have no name!@my-release-mongodb-sharded-shard0-data-0:/$ mongo admin --username root -p mongodb123 --host 10.244.1.35 --port 27017
MongoDB shell version v4.4.13
connecting to: mongodb://10.244.1.35:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 10.244.1.35:27017, connection attempt failed: SocketException: Error connecting to 10.244.1.35:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$

What command will help me checl the permissions on mount volumes?

**Comment by javsalgar** [comment]
Hi,

In diagnostic mode the nodes don't get initialized. What I was thinking is on you executing `kubectl exec -ti <node> bash` and then doing `ls -la` in the volume folders to see the permissions.

**Comment by Shilagrawal** [comment]
I have no name!@my-release-mongodb-sharded-shard0-data-0:/bitnami$ mongo admin --username root -p mongodb123 --host 10.244.4.11 --port 27017
MongoDB shell version v5.0.8
connecting to: mongodb://10.244.4.11:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 10.244.4.11:27017, connection attempt failed: SocketException: Error connecting to 10.244.4.11:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1
I have no name!@my-release-mongodb-sharded-shard0-data-0:/bitnami$ ls -la
total 0
drwxr-xr-x 3 root root 21 Apr 29 18:08 .
drwxr-xr-x 1 root root 35 May 17 08:33 ..
drwx--S--- 2 root 1001  6 May 17 08:33 mongodb
I have no name!@my-release-mongodb-sharded-shard0-data-0:/bitnami$ cd ..
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$ pwd
/
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$ ls -la
total 0
drwxr-xr-x   1 root root  35 May 17 08:33 .
drwxr-xr-x   1 root root  35 May 17 08:33 ..
-rw-rw-r--   1 root root   0 Apr 29 18:08 .dbshell
-rwxr-xr-x   1 root root   0 May 17 08:33 .dockerenv
drwxrwxr-x   2 root root   6 Apr 29 18:08 .mongodb
-rw-rw-r--   1 root root   0 Apr 29 18:08 .mongorc.js
-rw-rw-r--   1 root root   0 Apr 29 18:08 .mongoshrc.js
drwxr-xr-x   1 root root  71 Apr 29 18:08 bin
drwxr-xr-x   3 root root  21 Apr 29 18:08 bitnami
drwxr-xr-x   2 root root   6 Mar 19 13:44 boot
drwxr-xr-x   5 root root 360 May 17 08:33 dev
drwxrwxr-x   2 root root   6 Apr 29 18:08 docker-entrypoint-initdb.d
drwxrwsrwx   3 root 1001  91 May 17 08:33 entrypoint
lrwxrwxrwx   1 root root  50 Apr 29 18:08 entrypoint.sh -> /opt/bitnami/scripts/mongodb-sharded/entrypoint.sh
drwxr-xr-x   1 root root  66 May 17 08:33 etc
drwxr-xr-x   2 root root   6 Mar 19 13:44 home
drwxr-xr-x   1 root root  30 Sep 25  2017 lib
drwxr-xr-x   2 root root  34 Apr 15 18:16 lib64
lrwxrwxrwx   1 root root  30 Apr 29 18:08 liblog.sh -> /opt/bitnami/scripts/liblog.sh
drwxr-xr-x   2 root root   6 Apr 15 18:16 media
drwxr-xr-x   2 root root   6 Apr 15 18:16 mnt
drwxrwxr-x   1 root root  21 Apr 29 18:07 opt
dr-xr-xr-x 786 root root   0 May 17 08:33 proc
drwx------   2 root root  37 Apr 15 18:16 root
drwxr-xr-x   1 root root  21 May 17 08:33 run
lrwxrwxrwx   1 root root  43 Apr 29 18:08 run.sh -> /opt/bitnami/scripts/mongodb-sharded/run.sh
drwxr-xr-x   1 root root  20 Apr 29 18:08 sbin
drwxr-xr-x   2 root root   6 Apr 15 18:16 srv
dr-xr-xr-x  13 root root   0 May 17 08:33 sys
drwxrwxrwt   1 root root   6 Apr 29 18:08 tmp
drwxrwxr-x   1 root root  66 Apr 29 18:07 usr
drwxr-xr-x   1 root root  30 Apr 15 18:16 var
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$

**Comment by Shilagrawal** [comment]
Without diagnostic mode if I dont use --set volumePermissions.enabled=true  option the pods run fine but after exec and trying to login to database it gives error  
mongo admin --username root -p mongodb123 --host 10.244.4.11 --port 27017
MongoDB shell version v5.0.8
connecting to: mongodb://10.244.4.11:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 10.244.4.11:27017, connection attempt failed: SocketException: Error connecting to 10.244.4.11:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1
----------------------------------------------------------------------------------------------------------------------------------
And if i use the option --set volumePermissions.enabled=true in helm command for install the pods state is crashinloop and kubectl logs show up error as 
mongodb 13:22:29.42 INFO ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb': Permission denied

**Comment by Shilagrawal** [comment]
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
scinia      252:0    0  104G  0 disk
scinib      252:16   0  104G  0 disk
scinic      252:32   0  504G  0 disk /bitnami/mongodb
nvme0n1     259:0    0   70G  0 disk
|-nvme0n1p1 259:1    0    1M  0 part
`-nvme0n1p2 259:2    0   70G  0 part /etc/hosts
nvme1n1     259:3    0 1000G  0 disk
nvme2n1     259:4    0 1000G  0 disk
nvme4n1     259:5    0 1000G  0 disk
nvme3n1     259:6    0 1000G  0 disk
nvme6n1     259:8    0 1000G  0 disk
nvme7n1     259:9    0 1000G  0 disk
nvme8n1     259:10   0 1000G  0 disk
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ chown -R 1001 /bitnami/mongodb
chown: cannot read directory '/bitnami/mongodb': Permission denied
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ cd /bitnami/mongodb
bash: cd: /bitnami/mongodb: Permission denied
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ id
uid=1001 gid=0(root) groups=0(root),1001
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$

**Comment by Shilagrawal** [comment]
@javsalgar  Any help further is much appreciated 
 securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30

This is the section I see in kubectl edit deployment section (given its helm way of install) and even when i exec to pod it said id as uid 1001 so looks like it runs bu user as 1001 which is having permission issues , Please note I am using CSI on top of K8s env to help create Persistent volumes

**Comment by javsalgar** [comment]
Thank you for the information. Could you show the information of 

```
ls /bitnami/mongodb/ -la
```

**Comment by Shilagrawal** [comment]
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ ls /bitnami/mongodb/ -la
ls: cannot open directory '/bitnami/mongodb/': Permission denied
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ ls -l
total 0
drwxr-xr-x.    1 root root  71 Apr 29 18:08 bin
drwxr-xr-x.    3 root root  21 Apr 29 18:08 bitnami
drwxr-xr-x.    2 root root   6 Mar 19 13:44 boot
drwxr-xr-x.    5 root root 360 May 18 14:17 dev
drwxrwxr-x.    2 root root   6 Apr 29 18:08 docker-entrypoint-initdb.d
drwxrwsrwx.    3 root 1001  91 May 18 14:17 entrypoint
lrwxrwxrwx.    1 root root  50 Apr 29 18:08 entrypoint.sh -> /opt/bitnami/scripts/mongodb-sharded/entrypoint.sh

**Comment by javsalgar** [comment]
Hi,

Definitely looks like a PVC or a cluster issue in the way the volumes are mounted. Could you try with a different volume provider?

**Comment by Shilagrawal** [comment]
@javsalgar  or anyone here who have deployed it very latest wit a week or 10 days and it works for them ?  I think there is something definitely wrong with the bitnami chart or some yaml file the init containers are not giving the permissions properly or some issue if you happen to deploy it this week or so latest ? as this did work for me a month back however this time i am facing issues

**Comment by javsalgar** [comment]
If you are using the GKE standard storage the `fsGroup` permissions should work without using the init container. We test it daily without issues.

**Comment by Shilagrawal** [comment]
@javsalgar  Thank you for all the responses so far, our CSI looks good FSgroup permission was also full from the SC to debug it. 
I am almost nearing to identify the problem but sharing some observations and below questions.

1) When i use  --set volumePermissions.enabled=true - pods crashes in loop to make it work : 
When i change the permissions of all statefulsets (configserver and shards) 
initContainers:
      - args:
        - -ec
        - |
          mkdir -p /bitnami/mongodb
          chmod 700 /bitnami/mongodb ---> here to 770 
Containers run fine and do not crashin loop so some permission issue with teh init container or Volumepermission string has some problem for sure.

2) When i dont use  --set volumePermissions.enabled=true  option pods run fine and i can exec and login to pods with "only" root user. 
looks like in this case the initcontainer doesnt execute not sure ?? 

Questions: 
1) **During helm install command if i want to create a user say mongodb and a password for user how do i do that ?** 
what --set option can i use? 
2) earlier i used helm install my-release bitnami/mongodb-sharded --namespace=mongodb --set global.storageClass=vxflexos-xfs **--set **mongodbRootPassword=mongodb123,mongodbUsername=mongodb,mongodbPassword=mongodb123,mongodbDatabase=ycsb****
which worked 2 months back, now it looks like some params have changed so i use 

--set auth.RootPassword=mongodbtest,mongodbUsername=mongodb,mongodbPassword=mongodb123,mongodbDatabase=ycsb
so to sets the rootpassword what i want to however doesn't create any user called mongodb to login to the pod 
Hence after we exec to pod only root user login works and no other user is created it seems 
mongo admin --username -p --host x.x.x.x --port 27017

**Comment by javsalgar** [comment]
About the dbUser, I think we don't currently have support for that. You would need to add a configMap or secret with init scripts commands that you require, for example, creating a user. Please check the `initScriptsSecret` value for example.
