### ISSUE TITLE
Why is one container the designated primary in a replica set

### ISSUE THREAD

**Issue by sventschui** [bitnami/bitnami-docker-mongodb#187]
This is not an issue but more a question on how the mongodb image is designed. Bitnami Community Forums tell me to open a GitHub Issue so here I am, not sure if this is the correct place to ask this question.

Why is there one container designated to be the primary in a replica set (One container is started as `MONGODB_REPLICA_SET_MODE=primary`)? What are the benefits over issuing the same `rs.initiate({ ..., members: [{...}, {...}, {...}], ... })` on startup of each node? Dynamic discovery? What if the cluster fails completely and the designated primary node doesn't start anymore for whatever reason: can then two remaining, designated secondary, nodes re-start the cluster?

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. Yes, this is the correct place to ask :) From a Kubernetes perspective, if we were to specify the list of all nodes in an environment variable (for example):

```
MONGODB_REPLICASET_MEMBERS=node1,node2,node3
```

Then, if we scale out the number of nodes, the environment variable would be updated to

```
MONGODB_REPLICASET_MEMBERS=node1,node2,node3,node4
```

That would mean that all of the containers would need to restart and reconfigure themselves with the updated information. Instead, with the configuration we have now, this would not happen and the new node would transparently add itself to the cluster without forcing a restart.

If, in the cluster, the node designated as primary fails, then a new one would be designated as primary, even though the environment variables and the pod name would not reflect that. In this case, the scaling out of the nodes would not work correctly because they would try to contact an incorrect primary. I think this is something that we should review to improve the resiliency of the deployment.

I will open a task to investigate this situation and see if we can add a logic to improve it.

**Comment by sventschui** [comment]
Thanks for the explanation. This makes sense now 👍 

One thing that is a bit unfortunate is that when the designated primary node comes up after a longer downtime it joins as secondary and due to its high priority immediately casts for a new election and will be primary again. The designated primary has a lot of things to catch up in the oplog and thus might not accept any writes for a certain period. (This is my understanding of how things work and I could only test parts of this theory, maybe I'm wrong in some points.) You might want to take this into account when thinking about making things more resilient.

If you have any ideas on how to improve resiliency keep me posted, happy to contribute!

**Comment by javsalgar** [comment]
Hi,

Thanks for the input, indeed, that's something we should consider if we go on with the major change in the chart. We will update this ticket if we decide moving forward with this approach.

**Comment by p4l1ly** [comment]
Hi, I can see an option of dynamic replica set mode in the code, which would perfectly solve these problems for the use cases which do not require the auto-scaling feature. The option unfortunately does not pass the `mongodb_validate` check. What do you think about adding `elif [[ "$MONGODB_REPLICA_SET_MODE" = "dynamic" ]]; then :` to the `mongodb_validate`?

I have another error case which really happened recently: The INITIAL_PRIMARY has died together with its storage. A new member with the same URL was started but another PRIMARY had already been elected. The newly started INITIAL_PRIMARY has created its own new singleton replica set with the same name. We've thus ended up with two PRIMARY nodes running, which confused the clients. I've simulated the situation with pure mongo without bitnami-docker-mongodb and everything worked beautifully: the new member has been automatically invited to the existing replica set by the current PRIMARY, which knew it via its inherited url.

**Comment by javsalgar** [comment]
Hi,

So, if I understand correctly, the issue occurred when the initial primary node and the storage disappeared, right?  I don't think this kind of cases are currently covered in the logic. I think that, for this scenario, it may require some sort of manual intervention. We'd like to make this kind of "diagnostic mode" easy in the chart. Which kind of storage were you using? Were you using local storage and the kubernetes node died?

**Comment by p4l1ly** [comment]
Yes, you understand the case correctly. And yes, we were using local storage (for performance reasons).

**Comment by javsalgar** [comment]
I will forward this to the rest of the engineering team to see what kind of improvements we could do for this kind of issues. However, at the moment I'm afraid that it may require manual intervention or maybe backup and restore to a new cluster.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
