### ISSUE TITLE
Distroless MongoDB

### ISSUE THREAD

**Issue by omymy1** [bitnami/bitnami-docker-mongodb#286]
gcr.io/distroless/static-debian10

use Google distroless debian docker container for creating Distroless MongoDB.
We know some features are not accessible in Distroless container(exec or bash).
but Distroless is only for security and security.
Please note down the future request, and to make it as soon as possible.

**Comment by hanumanjiblog** [comment]
Yes, Distroless MongoDB Really needed for security. 
Bitnami team please make a Dockerfile for that.

@omymy1 Thanks for your suggestions.

**Comment by malaxmimdkm** [comment]
Google distroless and bitnami-docker-mongodb is really useful docker container. If we mix Google distroless security and bitnami-docker-mongodb database then it will really awesome. Really I need it.

**Comment by rupamking1** [comment]
great idea man, I already use google distroless for my each project just for security.
but MongoDB has less security and no two factor authentication and incorrect password ip block and more and more.

but Google Distroless did not have Shell or bash. It will make MongoDB much secure.
Implement it

**Comment by Mauraza** [comment]
Hi @omymy1, @malaxmimdkm, @hanumanjiblog, and @rupamking1,

Did you try a create a new image with Google distroless using the image of bitnami/mongodb?

**Comment by omymy1** [comment]
Hello @Mauraza,
I tried some time but it throw some error, Please send me a dockerfile with Google Distroless image.

**Comment by malaxmimdkm** [comment]
@Mauraza I tried but I watch some docker build and run error.
Please create a dockerfile so that will so so helpful for us.

**Comment by Mauraza** [comment]
Hi @omymy1 and @malaxmimdkm,

Sorry, I've done some more research about Google distroless, is an image, we use bitnami/minideb. You can try to change but I don't know if that works. 

Please check this documentation:
- https://github.com/bitnami/bitnami-docker-mongodb#why-use-bitnami-images
- https://github.com/bitnami/minideb#why-use-minideb

**Comment by malaxmimdkm** [comment]
is minideb secure like Google distroless

**Comment by Mauraza** [comment]
Hi @malaxmimdkm,

Bitnami releases a new revision for all the container images periodically, see Bitnami releases a new revision (-rXX) for all the container images on daily basis, see https://github.com/bitnami/bitnami-docker-mongodb/commits/master. The main reason to follow this approach is to ensure all the bundled system packages are updated to the latest available version.

This method doesn't guarantee there are no vulnerabilities in all of them since there are some packages with known vulnerabilities that are not fixed in the Debian OS. In those cases, we can't do anything apart from wait until a new version patching the issue appears in the system package manager of the distro.
On the other hand, there is another option that is to find a vulnerability in the application code or in a library, in that case from Bitnami the only thing we can do is wait for a new upstream version to be released.

You can find more info about Bitnami processes regarding CVEs and Vulnerability scanners at https://docs.bitnami.com/kubernetes/open-cve-policy/

**Comment by malaxmimdkm** [comment]
Please make it

**Comment by carrodher** [comment]
Unfortunately, this is not something we will include in our roadmap in the short nor middle term. Currently, most of the bitnami container images are based on Debian (built on a daily basis to include the latest system packages).

In the same way, when it is possible we built the containers based on scratch (see https://github.com/bitnami/bitnami-docker-wavefront-kubernetes-collector/blob/a1e847ee7d4b87284b5792824e986ed221ad9f5c/1/scratch/Dockerfile#L1) but this is not possible in complex infrastructure images since an underlying OS is needed.

In the case of MongoDB, all the configuration and initialization logic is present in this repository, you can try creating a new _Dockerfile_ based on distroless and modifying the scripts is needed, but It is not something that we are going to address as a new supported distro for our images.
