### ISSUE TITLE
Unable to run mongodb container as root

### ISSUE THREAD

**Issue by kbiernat** [bitnami/bitnami-docker-mongodb#297]
**Description**

I'm trying to run mongo container as root, to work around some issues with glusterfs-backed PVC. But this also applies with local docker run.
The problem is, /opt/bitnami/mongodb/conf/mongodb.conf is owned by root, with 660 permissions, so MONGODB_DAEMON_USER can't read it, once it's run via `gosu "$MONGODB_DAEMON_USER" /opt/bitnami/mongodb/bin/mongod --config=/opt/bitnami/mongodb/conf/mongodb.conf`

I want to avoid initContainer hacks in k8s too.

This is what I see when trying to run it manually from within container (all env vars loaded)

```
# gosu mongo /opt/bitnami/mongodb/bin/mongod --config=/opt/bitnami/mongodb/conf/mongodb.conf       
Error opening config file: Permission denied
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
# ls -l /opt/bitnami/mongodb/conf/mongodb.conf 
-rw-rw---- 1 root root 1018 Oct  5 06:45 /opt/bitnami/mongodb/conf/mongodb.conf
```

**Steps to reproduce the issue:**

1. docker run -ti --rm --user=0:0 docker.io/bitnami/mongodb:4.4.9-debian-10-r15

**Describe the results you received:**

```
$ docker run -ti --rm --user=0:0 docker.io/bitnami/mongodb:4.4.9-debian-10-r15
mongodb 07:50:05.88 
mongodb 07:50:05.88 Welcome to the Bitnami mongodb container
mongodb 07:50:05.88 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 07:50:05.88 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 07:50:05.89 
mongodb 07:50:05.89 INFO  ==> ** Starting MongoDB setup **
mongodb 07:50:05.91 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 07:50:06.05 INFO  ==> Initializing MongoDB...
mongodb 07:50:06.07 INFO  ==> Deploying MongoDB from scratch...

$ echo $?
2
```

**Describe the results you expected:**

I expected mongodb to start :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Irrelevant, happens in local docker but also on-prem kubernetes cluster with securityContext.runAsUser: 0

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by migruiz4** [comment]
Hi @moule3053,

Thank you for your feedback, but I am missing some context about your case. 

The issue described by @kbiernat  happens when trying to run the MongoDB container as root, but in your comment you mention your Kubernetes cluster only can run non-root pods, so I think you might be facing a different issue.

**Comment by moule3053** [comment]
Hi @migruiz4 Yes, my setup is different from that of @kbiernat , but I thought the root cause might be the same. As mentioned in the above issue "/opt/bitnami/mongodb/conf/mongodb.conf is owned by root, with 660 permissions, so MONGODB_DAEMON_USER can't read it". Similarly, in my case, even though the ownership of the `/opt/bitnami` directory is changed the user can't still read the config file.

**Comment by migruiz4** [comment]
Hi @moule3053,

Yes, I would appreciate it if you could open a separate issue so we can continue this discussion there.

Please include in the issue description any significant details about your case, including the motivation to add `RUN chown 1001:1001 -R /opt/bitnami` to the MongoDB.

**Comment by zloyded** [comment]
+ please fix permission ussie while mount volumes by docker compose
"Operation not supported" and container will fail, with error assertion failed.

**Comment by migruiz4** [comment]
Hi @zloyded,

Could you please open a separate issue providing more details about your case? (Steps to reproduce, detailed logs, version of the image)

I would like to keep this issue on the original topic, which is MongoDB failing to run as root.

**Comment by carrodher** [comment]
Thanks for reporting this issue. After some time and internal discussions, and due to we are a small team and the rest of the priorities we have in our backlog, this task was not prioritized and there are no plans to work on it in the short/mid term. We decided not to work on it because we only officially support one format which is the one implemented in our test & release pipeline (non-root).

Being said that, would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
