### ISSUE TITLE
Enabling oplog support?

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/bitnami-docker-mongodb#48]
It's fairly common to want to enable the oplog for mongodb. The docs mention replication but also covering oplog explicitly in the documentation would be helpful.

https://docs.mongodb.com/v3.0/core/replica-set-oplog/

**Comment by juan131** [comment]
Bitnami has some documentation about OpLog at the Multi-Tier solution documentation:
https://docs.bitnami.com/google-templates/infrastructure/mongodb/#how-to-recover-your-database-from-mongodb-oplog-operation-log
However, I agree with you. There should be included a section in the README.md file covering it.

**Comment by sa-mao** [comment]
Hello, I'm currently using the bitnami image, and was wondering how can we enable oplog.

**Comment by andresbono** [comment]
Hi @sa-mao, you can check if you have oplog enabled by executing:

```
> use local
> db.oplog.rs.find()
```

If you get an empty result, `oplog` is disabled.

To enable it, you need to set the replica set to "primary". In order to do so, you can set the env-var with the following value `MONGODB_REPLICA_SET_MODE=primary`. This will enable replica set options in the MongoDB configuration file:

```
# replica set options
replication:
  replSetName: replicaset
  ...
```

Once enabled, you can query MongoDB again to check oplogs.

**Comment by sa-mao** [comment]
Hi @andresbono thanks for your help. I just tried now and It is actually enabled!

**Comment by andresbono** [comment]
Great to hear!
