### ISSUE TITLE
Add editor to image?

### ISSUE THREAD

**Issue by whitecolor** [bitnami/bitnami-docker-mongodb#79]
Couldn't find a way to edit mongodb config file (no vi, nano..)

Probably should install vim for example. Maybe to have it baked in?

**Comment by chipironcin** [comment]
Hi @whitecolor 
In order to keep the base image small, we only ship required packages for running the applications.

If you mounted the conf folder, you can edit the files from your host system.
If you want to use a specific config file you can follow the instructions in the README.md at https://github.com/bitnami/bitnami-docker-mongodb#configuration-file

If you are just testing the image and trying out different configurations, you can enter the container and execute the following to have an editor:
```
# Install an editor (vim, emacs, nano...)
install_packages vim
```

**Comment by sebgoa** [comment]
@whitecolor is that answer fine with you ? can we close the issue ?
