### ISSUE TITLE
How to pass custom parameters to mongod (helm or Docker)

### ISSUE THREAD

**Issue by eldada** [bitnami/bitnami-docker-mongodb#92]
**Description**
I want to be able to set custom run time parameters to `mongod` like `--wiredTigerCacheSizeGB` for better control in my Kubernetes environment (I use your public helm chart).
I don't see any way to pass such (like `--wiredTigerCacheSizeGB=6GB`) to the running process.

**Steps to reproduce the issue:**
Just deploy the bitnami mongodb helm chart

**Describe the results you received:**
MongoDB runs with default configuration

**Describe the results you expected:**
Option to pass custom run time parameters

**Additional information you deem important (e.g. issue happens only occasionally):**
Running in Kubernetes. Deployed with helm chart.

**Version**
Kubernetes 1.9.6
Helm chart 1.0.0
MongoDB 3.7.3

**Note**: If there's a simple way to do this for Docker, I can submit a pull request to the helm chart.

**Comment by andresbono** [comment]
Hi @eldada, thanks for taking the time to fill this request. It totally makes sense to have an option to include extra runtime options that you may want to set. We will evaluate the inclusion of this feature in next releases and we will let you know about it.

Thanks again!
-Andrés B.

**Comment by eldada** [comment]
I just noticed https://github.com/bitnami/bitnami-docker-mongodb/pull/90.
Can this solve the issue? If so, how can it be aded to the helm chart? I guess environment variable that will be picked up by the `app-entrypoint.sh` script...

**Comment by andresbono** [comment]
> I just noticed #90.
Can this solve the issue?

Kind of, @eldada! Just for the sake of unifying this requested feature with the way other containers already do, we are going to implement this with an environment variable.

We will keep you in the loop.
-Andrés B.

**Comment by andresbono** [comment]
Hi again @eldada, since [3.6.3-r6](https://github.com/bitnami/bitnami-docker-mongodb/releases/tag/3.6.3-r6) and [3.7.3-r2](https://github.com/bitnami/bitnami-docker-mongodb/releases/tag/3.7.3-r2) releases you can use extra options to be passed to the `mongod` daemon.

You can now use the `MONGODB_EXTRA_FLAGS` environment variable. For more details, it is documented in the [README.md](https://github.com/bitnami/bitnami-docker-mongodb#user-content-passing-extra-command-line-flags-to-mongod-startup).

To use this with helm, check this PR: https://github.com/kubernetes/charts/pull/5012.

Thanks again for your valuable feedback!
-Andrés B.

**Comment by eldada** [comment]
Hi @andresbono - this is great news! Exactly what I needed. I will start using this and let you know of any issues. Closing.
